-- =============================================================================
-- Subscription Analytic System — DBMS Project
--
-- Canonical analytics SQL has moved to:
--   database/analytics_queries.sql
--
-- Import and run queries from that file.
-- Core queries (1–8) are unchanged in meaning and match the Express API.
-- =============================================================================

-- See: ../database/analytics_queries.sql
